FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env
WORKDIR /

# Copy everything
COPY . ./

WORKDIR /api/OntologyAPI
# Build and publish a release
RUN dotnet publish -c Release -o publishContainer

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:10.0
RUN apt-get update && apt-get -y upgrade
WORKDIR /frontend/ontology
COPY --from=build-env /api/OntologyAPI/publishContainer .
ENTRYPOINT ["dotnet", "OntologyAPI.dll"]