FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /

# Copy everything
COPY . ./

WORKDIR /api/OntologyAPI
# Build and publish a release
RUN dotnet publish -c Release -o publishContainer

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /frontend/ontology
COPY --from=build-env /api/OntologyAPI/publishContainer .
ENTRYPOINT ["dotnet", "OntologyAPI.dll"]